[package]
name = "threads"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "threads"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

threads_integrity = { workspace = true } 
